{% set name = "biopython" %}
{% set version = "1.86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93a50b586a4d2cec68ab2f99d03ef583c5761d8fba5535cb8e81da781d0d92ff

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - wheel
    - python
    - setuptools  >=70.1
  run:
    - python
    - numpy

# Test file skipping due to missing import dependencies which are not in main channel
{% set test_files_to_skip = "--ignore=test_BWA_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_MySQLdb.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_MySQLdb_online.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_mysql_connector.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_mysql_connector_online.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_psycopg2.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_BioSQL_psycopg2_online.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_ClustalOmega_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Clustalw_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Dialign_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Emboss.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_EmbossPhylipNew.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Fasttree_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_MSAProbs_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Mafft_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Muscle_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_NCBI_BLAST_tools.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PAML_tools.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PDB_PSEA.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PDB_binary_cif.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PDB_internal_coords.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Phylo_CDAO.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Phylo_igraph.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Phylo_matplotlib.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Phylo_networkx.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PopGen_GenePop.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_PopGen_GenePop_EasyController.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Prank_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Probcons_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_TCoffee_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_Tutorial.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_XXmotif_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_mmtf.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_mmtf_online.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_phenotype_fit.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_phyml_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_raxml_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_samtools_tool.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_GraphicsBitmaps.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_ColorSpiral.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_GenomeDiagram.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_GraphicsChromosome.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_GraphicsDistribution.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_GraphicsGeneral.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_KGML_graphics.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=test_KGML_graphics_online.py" %}

# Tests skipped due to assertion errors, test files not found and general error
{% set tests_to_skip = "test_orchid_est" %}
{% set tests_to_skip = tests_to_skip + " or test_pcr_primers" %}
{% set tests_to_skip = tests_to_skip + " or test_retrieve_pdb_file_mmtf" %}
{% set tests_to_skip = tests_to_skip + " or test_search_with_fields" %}
{% set tests_to_skip = tests_to_skip + " or test_reading" %}
{% set tests_to_skip = tests_to_skip + " or test_random" %}
{% set tests_to_skip = tests_to_skip + " or test_random_sequences" %}
{% set tests_to_skip = tests_to_skip + " or test_pubmed_search_porin" %}
{% set tests_to_skip = tests_to_skip + " or test_get_mmcif_file_path_for" %}
{% set tests_to_skip = tests_to_skip + " or test_pubmed_search_bioruby" %}
{% set tests_to_skip = tests_to_skip + " or test_pubmed_search_togows" %}
{% set tests_to_skip = tests_to_skip + " or test_epost" %}
{% set tests_to_skip = tests_to_skip + " or test_webenv_search" %}
{% set tests_to_skip = tests_to_skip + " or test_coord_space" %}
# E       urllib.error.HTTPError: HTTP Error 429: Too Many Requests
{% set tests_to_skip = tests_to_skip + " or EntrezOnlineCase" %}
{% set tests_to_skip = tests_to_skip + " or test_load_database_with_tax_lookup" %}
# E       urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
{% set tests_to_skip = tests_to_skip + " or TestMotifWeblogo" %}
# E           AttributeError: module 'unittest' has no attribute 'patch'
{% set tests_to_skip = tests_to_skip + " or test_retrieve_pdb_file_bad_url" %}
{% set tests_to_skip = tests_to_skip + " or test_retrieve_pdb_file_not_existing" %}
# E           http.client.RemoteDisconnected: Remote end closed connection without response
{% set tests_to_skip = tests_to_skip + " or test_short_query" %}

test:
  source_files:
    - Tests
  imports:
    - Bio
    - Bio._utils
    - Bio.Affy
    - Bio.Align
    - Bio.Align.analysis
    - Bio.Align.bigbed
    - Bio.Align.nexus
    - Bio.Align.substitution_matrices
    - Bio.AlignIO
    - Bio.AlignIO.ClustalIO
    - Bio.AlignIO.EmbossIO
    - Bio.AlignIO.Interfaces
    - Bio.AlignIO.MafIO
    - Bio.AlignIO.MauveIO
    - Bio.AlignIO.NexusIO
    - Bio.AlignIO.PhylipIO
    - Bio.Blast
    - Bio.Blast.NCBIXML
    - Bio.codonalign.codonalignment
    - Bio.codonalign.codonseq
    - Bio.Data
    - Bio.Data.CodonTable
    - Bio.Data.IUPACData
    - Bio.Data.PDBData
    - Bio.Emboss
    - Bio.Entrez
    - Bio.ExPASy
    - Bio.File
    - Bio.GenBank
    - Bio.GenBank.Scanner
    - Bio.KEGG
    - Bio.KEGG.KGML
    - Bio.KEGG.KGML.KGML_parser
    - Bio.KEGG.KGML.KGML_pathway
    - Bio.KEGG.REST
    - Bio.motifs
    - Bio.Nexus
    - Bio.Nexus.StandardData
    - Bio.Nexus.Trees
    - Bio.NMR
    - Bio.Pathway
    - Bio.Pathway.Rep.Graph
    - Bio.Pathway.Rep.MultiGraph
    - Bio.PDB
    - Bio.PDB._bcif_helper
    - Bio.PDB.AbstractPropertyMap
    - Bio.PDB.Atom
    - Bio.PDB.ccealign
    - Bio.PDB.Chain
    - Bio.PDB.Entity
    - Bio.PDB.ic_data
    - Bio.PDB.ic_rebuild
    - Bio.PDB.internal_coords
    - Bio.PDB.kdtrees
    - Bio.PDB.MMCIF2Dict
    - Bio.PDB.MMCIFParser
    - Bio.PDB.Model
    - Bio.PDB.NACCESS
    - Bio.PDB.NeighborSearch
    - Bio.PDB.parse_pdb_header
    - Bio.PDB.PDBExceptions
    - Bio.PDB.PDBIO
    - Bio.PDB.PDBList
    - Bio.PDB.PDBParser
    - Bio.PDB.PICIO
    - Bio.PDB.Polypeptide
    - Bio.PDB.PSEA
    - Bio.PDB.qcprot
    - Bio.PDB.Residue
    - Bio.PDB.ResidueDepth
    - Bio.PDB.SASA
    - Bio.PDB.SCADIO
    - Bio.PDB.Selection
    - Bio.PDB.Structure
    - Bio.PDB.StructureBuilder
    - Bio.PDB.vectors
    - Bio.phenotype
    - Bio.Phylo
    - Bio.Phylo._io
    - Bio.Phylo._utils
    - Bio.Phylo.Consensus
    - Bio.Phylo.PAML
    - Bio.Phylo.PAML._paml
    - Bio.Phylo.TreeConstruction
    - Bio.PopGen
    - Bio.PopGen.GenePop
    - Bio.Restriction
    - Bio.Restriction.PrintFormat
    - Bio.Restriction.Restriction
    - Bio.Restriction.Restriction_Dictionary
    - Bio.SCOP
    - Bio.SCOP.Residues
    - Bio.SearchIO
    - Bio.SearchIO._index
    - Bio.SearchIO._model
    - Bio.SearchIO._utils
    - Bio.SearchIO.BlastIO.blast_tab
    - Bio.Seq
    - Bio.SeqFeature
    - Bio.SeqIO
    - Bio.SeqIO._index
    - Bio.SeqIO.FastaIO
    - Bio.SeqIO.InsdcIO
    - Bio.SeqIO.SffIO
    - Bio.SeqRecord
    - Bio.Sequencing
    - Bio.SeqUtils
    - Bio.SeqUtils.CheckSum
    - Bio.SeqUtils.lcc
    - Bio.SVDSuperimposer
    - Bio.SwissProt
    - Bio.UniProt
    - BioSQL
  requires:
    - pip
    - pytest <9
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # cd into Tests folder due to relative paths in tests
    - cd Tests && pytest . -v -k "not ({{ tests_to_skip }})" {{ test_files_to_skip }}

about:
  home: https://biopython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Collection of freely available tools for computational molecular biology
  description: |
    Biopython is a collection of freely available Python tools for
    computational molecular biology
  doc_url: https://biopython.org
  dev_url: https://github.com/biopython/biopython

extra:
  recipe-maintainers:
    - souravsingh
    - peterjc