travis:
  secure:
    BINSTAR_TOKEN: vIeM/kGrLrhY4A9YtwixozstRAEXnP54/+8rBk54ba7YZh7weZdn4OBJFq4XNLg9bGd7nB34ko+IV3DKw0zd4tLUUROU6r/foKJcrSzOw7p2t9P1Z+sKE0MeTc7M3ZAEYW7aK2iBaFDEAAweBgY4W22cr5s3cArozAR/f+1HYbKH1IzPpQW94xOxO0uf9sGl/5N1luHk/yc8Kpi7fPde+3/PxSBEWVg0mFymOo8cDGZhrU2TUNieeYxXc1efoli/EHT7Ujmej1eDU+TXyyXFO2ZaHTA+6HTcYGOm0s+rnjIVBn+Ass3piQBuoJ5L+9t2yS0nPyGDLn18hXl4dzZpfDdNhiZ2bmwUZtiR0EX00Un4hgeXS03SUcohCc4YiZzXoOGztPP7SUoU3GKewXsctqsx4aKphDJi0u2WOPMXLCDPkGFmRtwzkxaXuk5k8gePCRCfVt6q5dOxakH+VwDZeF+t3sYZhdiul0acYL2WmtT2SnwAwNHNJdi8plbfhNCRwY2/ICXUahwqNQLQroq4VULFBX1K9rBbzTNBLbINWAlWbMU+5vZ8T/ADhyffAidtuGd1JQTomm8dXetOzfbA6WujUpSgF+T41FHvuX4HentWdSnEcf+fK5BRoh6oL4Kr4YcEO/ZCYHY290ntyAawO48rEdh8qcNaQy0iLIR3X0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
