travis:
  secure:
    BINSTAR_TOKEN: uecLY6ppqNGMEM2UUEfpEyf2p6Lk5ZvS/xMGHIw6MCdv8WCtIpZABl2TldIpsTFjjtnPZmQ2BXHcXcz0uZnzqf5wFO4nhivjbITvqIGqIEoZlK+GGvw+RjitHVW75A4dVUcYPcGRANNWPa64eav+XbKF3mFyh4pBYatAV0JYEVbjdSNciHxaJMMMwa7DIOzz7Ynd+fAgtZXJHllWGdDM9Apwt6U62uFBA9zAt+2eBIaqNaI7jJeRt63bP9akXq6Jg+3vNRJ7coW0PlZ6lkqwt+T3lKeM7fug2rE7wjgBcGFwAqoILAldJB5l+oxlDhFYiOB32WUrGbv2ETcpT4LOu+C8zszj45Z4XzBX7/EaIMPPwmi5mHCW/RovBTF8gIZiBOPEcaPh0r9nwFadB3/bbfojM0kCHC9Pucsr0TnDTkA6fiQ+2jILN1Mbdw7FW2VTp0Uv1A4J5Fk/IweNr+T1uodbqgJcZ4fU4pvJniELRzaxsuQXVMmglTHyXdtqAI/Brzd2L9dd2iGOHUm3mqhmo+N2GtPOY2T0CSA5pHKTqbx/xwCI0k9E30pQ+eIveAlt/zOWiY2VGTkE9h1yQ0QRAEgvG7mnSoeeSy+Pii/S18GYO5JPmJqMGlMbIer9aEGUflPyVj9AHO+cP1B8YHA3QIva6UTZaasfbO8WBp6g/tQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
